# Deployment for Banshy Backend

apiVersion: apps/v1
kind: Deployment # Kind of resource to be created, in this case, a deployment
metadata:
  name: banshy-deployment # Name of the deployment, appears on the result of : kubectl get deployments
  labels:
    app: banshy-container # Tag that will be used to identify the deployment in the service
spec:
  replicas: 3 # Number of replicas to be created
  selector:
    matchLabels:
      app: banshy-container
  strategy:
    type: RollingUpdate
    rollingUpdate: # Rolling update strategy
      maxUnavailable: 1 # Number of pods that can be unavailable during the update
      maxSurge: 1 # Number of pods that can be created above the desired number of pods
  template:
    metadata:
      labels:
        app: banshy-container
    spec:
      containers:
        - image: kiki2956/banshy-backend:latest # Image to be used in the container. The image is hosted my Docker Hub.
          name: banshy-backend
          livenessProbe:
            httpGet: # Probe to check if the container is alive
              path: /isAlive
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
      restartPolicy: Always
