# Secret for MySQL database

apiVersion: v1
kind: Secret # Kind of resource to be created, in this case, a secret
metadata:
  name: mysql-db-secret # Name of the secret
type: Opaque # Type of the secret, opaque means that the data is encoded in base64
data:
  mysql-root-password: cm9vdA== # Root password for the MySQL database in base64
